version: "3.0"

services:
  mysql-server:
    container_name: mysql-server
    build: 
      context: ./mysql
      args: 
        MYSQL_VERSION: ${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_LOG_PATH}:/var/log/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
