version: "3.0"

services:
  mysql-server:
    container_name: mysql-server
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_LOG_PATH}:/var/log/mysql
      - ${MYSQL_CONFIG_PATH}/my.cnf:/etc/mysql/my.cnf
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'db'
    
